pork_names = [
    "pork",
    "bacon",
    "pork bacon",
    "streaky bacon",
    "back bacon",
    "ham",
    "pork ham",
    "prosciutto",
    "jamón",
    "jamón serrano",
    "jamón ibérico",
    "sausage",
    "pork sausage",
    "chorizo",
    "italian sausage",
    "breakfast sausage",
    "bratwurst",
    "pepperoni",
    "salami",
    "genoa salami",
    "hard salami",
    "prosciutto",
    "lard",
    "pancetta",
    "serrano ham",
    "jamón ibérico",
    "coppa (capicola)",
    "mortadella",
    "pork rinds",
    "pork loin",
    "pork chops",
    "pork shoulder",
    "boston butt",
    "picnic shoulder",
    "pork belly",
    "head cheese (brawn)",
    "pâté",
    "tasso",
    "fatback",
    "guanciale",
    "speck",
    "pork floss (rousong)",
    "pork pie",
    "souse",
    "gelatin"
]

non_pork = [
    "plant-based",
    "beef bacon",
    "turkey bacon",
    "chicken bacon",
    "duck bacon",
    "beef ham",
    "turkey ham",
    "chicken ham",
    "beef sausage",
    "turkey sausage",
    "chicken sausage",
    "duck sausage",
    "lamb sausage",
    "vegan sausage",
    "vegetarian sausage",
    "beef pepperoni",
    "turkey pepperoni",
    "chicken pepperoni",
    "vegan pepperoni",
    "vegetarian pepperoni",
    "beef salami",
    "turkey salami",
    "chicken salami",
    "duck salami",
    "vegan salami",
    "vegetarian salami",
    "turkey prosciutto",
    "duck prosciutto",
    "vegan prosciutto",
    "vegetarian prosciutto",
    "beef chorizo",
    "turkey chorizo",
    "chicken chorizo",
    "vegan chorizo",
    "vegetarian chorizo",
    "beef mortadella",
    "turkey mortadella",
    "chicken mortadella",
    "vegan mortadella",
    "vegetarian mortadella"
]
